spring:
  data:
    mongodb:
      uri: mongodb://myscrypt-real:myscrypt2021@cluster0-shard-00-00.pug2j.mongodb.net:27017,cluster0-shard-00-01.pug2j.mongodb.net:27017,cluster0-shard-00-02.pug2j.mongodb.net:27017/myscrypt-db?ssl=true&replicaSet=atlas-t8f1k8-shard-0&authSource=admin&retryWrites=true&w=majority
